# Generated by Django 5.0.6 on 2025-03-31 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid_user', models.TextField(unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email_id', models.TextField(unique=True)),
                ('mobile_no', models.CharField(unique=True)),
                ('password_hash', models.TextField()),
                ('gender', models.IntegerField()),
                ('user_referral_code', models.TextField(null=True, unique=True)),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='UMS.usermodel')),
            ],
            options={
                'db_table': 'ums_user',
            },
        ),
        migrations.CreateModel(
            name='UserReferrer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrer', to='UMS.usermodel')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_users', to='UMS.usermodel')),
            ],
            options={
                'db_table': 'ums_user_refer',
            },
        ),
        migrations.CreateModel(
            name='UserRefreshToken',
            fields=[
                ('refresh_token', models.TextField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='refresh_user', to='UMS.usermodel')),
            ],
            options={
                'db_table': 'ums_user_refresh_token',
            },
        ),
    ]
